language: python

python:
  - "3.9"
env:
  - SECRET_KEY='TEST'
services:
  - postgresql
install:
  - pip install -r requirements.txt

script:
  - python manage.py test

before_script:
  - psql -c 'create database travis_ci_test'; -U postgres
